spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=LUDO_DB;encrypt=false
    username: LUDO_USER
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
  application:
    name: RestLudotheque